import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import Content from '../components/Content';
import { Fragment } from 'react';
import Header from '../components/Header';

const inter = Inter({ subsets: ['latin'] });

interface Props {
    newWebtoon: WebtoonProject.newWebtoon[];
}

export default function Home({ newWebtoon }: Props) {
    console.log('Props', newWebtoon[0].title);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Fragment>
                {/* 헤더 네브바 => _app.tsx에 전역으로 생성*/}
                {/* <Header /> */}

                {/* 콘텐트 메인 */}
                <Content newWebtoon={newWebtoon} />

                {/* 푸터  => 이것도 아마 _app.tsx에 전역으로 생성할듯*/}
            </Fragment>
        </>
    );
}

export async function getStaticProps() {
    //api로 route불러오기

    console.log('getStaticProps');
    // const newWebtoon = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/new`) //
    //     .then((response) => response.json());

    const newWebtoon = await fetch(`${process.env.NEXT_PUBLIC_OPEN_URL}?service=kakao`) //
        .then((response) => response.json());

    // webtoons.webtoons
    console.log('asdfasdfasdf', newWebtoon.webtoons);
    return {
        props: { newWebtoon: newWebtoon.webtoons },
    };
}
